server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/formations?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
